"""empty message

Revision ID: bb8990856173
Revises: 
Create Date: 2024-12-16 22:20:40.278361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8990856173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penyewa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_penyewa', sa.String(length=80), nullable=False),
    sa.Column('no_hp', sa.String(length=80), nullable=False),
    sa.Column('alamat', sa.String(length=80), nullable=False),
    sa.Column('banyak_box', sa.Integer(), nullable=False),
    sa.Column('tipe_box', sa.String(length=80), nullable=False),
    sa.Column('tanggal_penyewaan', sa.String(length=80), nullable=False),
    sa.Column('lama_penitipan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penyewa')
    # ### end Alembic commands ###
