"""empty message

Revision ID: bf517c801016
Revises: bb8990856173
Create Date: 2024-12-25 15:29:25.677918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf517c801016'
down_revision = 'bb8990856173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('penyewa', schema=None) as batch_op:
        batch_op.drop_constraint('fk_penanggung_jawab', type_='foreignkey')
        batch_op.drop_column('penanggung_jawab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penanggung_jawab', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key('fk_penanggung_jawab', 'users', ['penanggung_jawab'], ['username'], ondelete='SET NULL')

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
